//
// Generated file, do not edit! Created by nedtool 5.5 from msg1.msg.
//

#ifndef __MSG1_M_H
#define __MSG1_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>msg1.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Msg1
 * {
 *     simtime_t residual_time;
 *     double serviceTime;
 *     simtime_t firstServerEntrance;
 * }
 * </pre>
 */
class Msg1 : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t residual_time;
    double serviceTime;
    ::omnetpp::simtime_t firstServerEntrance;

  private:
    void copy(const Msg1& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Msg1&);

  public:
    Msg1(const char *name=nullptr, short kind=0);
    Msg1(const Msg1& other);
    virtual ~Msg1();
    Msg1& operator=(const Msg1& other);
    virtual Msg1 *dup() const override {return new Msg1(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getResidual_time() const;
    virtual void setResidual_time(::omnetpp::simtime_t residual_time);
    virtual double getServiceTime() const;
    virtual void setServiceTime(double serviceTime);
    virtual ::omnetpp::simtime_t getFirstServerEntrance() const;
    virtual void setFirstServerEntrance(::omnetpp::simtime_t firstServerEntrance);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Msg1& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Msg1& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MSG1_M_H

